### ISSUE TITLE
Yo sup rouxhaver

### ISSUE THREAD

**Issue by JayisTypeShit** [8000-20/Scripts#1]
Pleaseeeeeeeeeeeee Make ANOTHERRRRR HACKER CHAT SCRIPT SO ME AND MY FRIENDS CAN CHAT PRIVATELY WITHOUT ANYBODY SEEING US IN LOGS

**Comment by JayisTypeShit** [comment]
Please bri

**Comment by 8000-20** [comment]
lol ill remake the script

**Comment by 8000-20** [comment]
done: https://github.com/8000-20/Scripts/blob/main/Hacker%20Chat%20v2.lua
